/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-04-04 06:35:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.connection.MyConnection;
import java.sql.ResultSet;

public final class SellOffer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/slider.jsp", Long.valueOf(1526141818000L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1526119552000L));
    _jspx_dependants.put("/head.jsp", Long.valueOf(1526189740000L));
    _jspx_dependants.put("/testimonials.jsp", Long.valueOf(1526111982000L));
    _jspx_dependants.put("/footer_script.jsp", Long.valueOf(1524274396000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1526118070000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("com.connection.MyConnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if lt IE 7]>      <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\"> <![endif]-->\r\n");
      out.write("<!--[if IE 7]>         <html class=\"no-js lt-ie9 lt-ie8\"> <![endif]-->\r\n");
      out.write("<!--[if IE 8]>         <html class=\"no-js lt-ie9\"> <![endif]-->\r\n");
      out.write("<!--[if gt IE 8]><!--> <html class=\"no-js\"> <!--<![endif]-->\r\n");
      out.write("    <head>\r\n");
      out.write("    \t<title>B2B Portal</title>\r\n");
      out.write("    \t\r\n");
      out.write("    \t");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">        \r\n");
      out.write("        <meta name=\"description\" content=\"GARO is a real-estate template\">\r\n");
      out.write("        <meta name=\"author\" content=\"Kimarotec\">\r\n");
      out.write("        <meta name=\"keyword\" content=\"html5, css, bootstrap, property, real-estate theme , bootstrap template\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700,800' rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->\r\n");
      out.write("        <link rel=\"shortcut icon\" href=\"#\" type=\"image/x-icon\">\r\n");
      out.write("        <link rel=\"icon\" href=\"#\" type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"UserTemplate/assets/css/normalize.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"UserTemplate/assets/css/font-awesome.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"UserTemplate/assets/css/fontello.css\">\r\n");
      out.write("        <link href=\"UserTemplate/assets/fonts/icon-7-stroke/css/pe-icon-7-stroke.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"UserTemplate/assets/fonts/icon-7-stroke/css/helper.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"UserTemplate/assets/css/animate.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"UserTemplate/assets/css/bootstrap-select.min.css\"> \r\n");
      out.write("        <link rel=\"stylesheet\" href=\"UserTemplate/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"UserTemplate/assets/css/icheck.min_all.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"UserTemplate/assets/css/price-range.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"UserTemplate/assets/css/owl.carousel.css\">  \r\n");
      out.write("        <link rel=\"stylesheet\" href=\"UserTemplate/assets/css/owl.theme.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"UserTemplate/assets/css/owl.transitions.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/lightslider.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"UserTemplate/assets/css/style.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"UserTemplate/assets/css/responsive.css\">\r\n");
      out.write("        <style>\r\n");
      out.write("\t\t#logo {\r\n");
      out.write("\t\theight:47px;\r\n");
      out.write("\t\twidth:176px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t#ssize{\r\n");
      out.write("\t\theight: 562px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t</style>");
      out.write("\r\n");
      out.write("\t        \r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"preloader\">\r\n");
      out.write("            <div id=\"status\">&nbsp;</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Body content -->\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"header-connect\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-5 col-sm-8  col-xs-12\">\r\n");
      out.write("                        <div class=\"header-half header-call\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                <span><i class=\"pe-7s-call\"></i> +91 1122334455</span>                                \r\n");
      out.write("                                <span><i class=\"pe-7s-mail\"></i> priyanka@gmail.com</span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-2 col-md-offset-5  col-sm-3 col-sm-offset-1  col-xs-12\">\r\n");
      out.write("                        <div class=\"header-half header-social\">\r\n");
      out.write("                            <!-- <ul class=\"list-inline\">\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-vine\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-linkedin\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-dribbble\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-instagram\"></i></a></li>\r\n");
      out.write("                            </ul> -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>        \r\n");
      out.write("        <!--End top header -->\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"navbar navbar-default \">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("                <div class=\"navbar-header\">\r\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navigation\">\r\n");
      out.write("                        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"index.html\"><img src=\"UserTemplate/assets/img/b2b logo.jpg\" alt=\"no image\" id=\"logo\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("                <div class=\"collapse navbar-collapse yamm\" id=\"navigation\">\r\n");
      out.write("                    <div class=\"button navbar-right\">\r\n");
      out.write("\t\t\t\t\t\t");

							if(session.getAttribute("email")!=null)
							{
								
      out.write("     \r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"navbar-btn nav-button wow bounceInRight login\" onclick=\"document.location='/B2B/LogoutServlet';\" data-wow-delay=\"0.45s\">Logout</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

							}
							else
							{
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"navbar-btn nav-button wow bounceInRight login\" onclick=\"document.location='Login.jsp';\" data-wow-delay=\"0.45s\">Login</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

							}
						
      out.write("                                                \t\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul class=\"main-nav nav navbar-nav navbar-right\">\r\n");
      out.write("                        <li class=\"wow fadeInDown\" data-wow-delay=\"0.2s\"><a class=\"\" href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"wow fadeInDown\" data-wow-delay=\"0.2s\"><a class=\"\" href=\"Categories.jsp\">Categories</a></li>\r\n");
      out.write("         \r\n");
      out.write("                        <li class=\"wow fadeInDown\" data-wow-delay=\"0.5s\"><a href=\"BuyOffers.jsp\">Buy Offer</a></li>\r\n");
      out.write("                        \r\n");
      out.write("                        <li class=\"wow fadeInDown\" data-wow-delay=\"0.5s\"><a href=\"SellOffer.jsp\">Sell Offer</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div><!-- /.navbar-collapse -->\r\n");
      out.write("            </div><!-- /.container-fluid -->\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- End of nav bar -->    ");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"slider-area\" id=\"ssize\">\r\n");
      out.write("            <div class=\"slider\">\r\n");
      out.write("                <div id=\"bg-slider\" class=\"owl-carousel owl-theme\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"item\"><img src=\"UserTemplate/assets/img/slide1/B2B-Banner2.jpg\" alt=\"GTA V\"></div>\r\n");
      out.write("                    <div class=\"item\"><img src=\"UserTemplate/assets/img/slide1/B2B-Banner1.png\" alt=\"The Last of us\"></div>\r\n");
      out.write("                    <div class=\"item\"><img src=\"UserTemplate/assets/img/slide1/silder-image-7.jpg\" alt=\"GTA V\"></div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("                   \r\n");
      out.write("            <div class=\"slider-content\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 col-sm-12\">\r\n");
      out.write("                                                                     \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- property area -->\r\n");
      out.write("        <div class=\"content-area home-area-1 recent-property\" style=\"background-color: #FCFCFC; padding-bottom: 55px;\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-10 col-md-offset-1 col-sm-12 text-center page-title\">\r\n");
      out.write("                        <!-- /.feature title -->\r\n");
      out.write("                        <h2>Sell Offers</h2>\r\n");
      out.write("                        <!-- <p>Nulla quis dapibus nisl. Suspendisse ultricies commodo arcu nec pretium. Nullam sed arcu ultricies . </p> -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"proerty-th\">\r\n");
      out.write("                    \t\r\n");
      out.write("                    \t<table style=\"width: 100%;margin: 5px;border: 1px solid black;\">\r\n");
      out.write("                    \t\t\r\n");
      out.write("                    \t\t<tr style=\"background-color: skyblue\">\r\n");
      out.write("                    \t\t\t<td style=\"width: 250px;\">Company</td>\r\n");
      out.write("                    \t\t\t<td>Sell Offer</td>\r\n");
      out.write("                    \t\t</tr>\r\n");
      out.write("                    \t");
 
                    		// select painter_photos.*,photo_categories.cat_name from painter_photos inner join photo_categories on painer_photos.cat_id=photo_categories.id order by painter_photos.id desc 0,8
                    	
                    		ResultSet rs=MyConnection.SelectQuery("select cb.*,cr.company_name from company_selloffer cb inner join company_registration cr on cb.company_id=cr.id");
                    	
                    		while(rs.next())
                    		{
                    			
                    			String description=rs.getString("description");
                    			String company_name=rs.getString("company_name");
                    			
                    			
                    			
      out.write("\r\n");
      out.write("                    \t\t\t<tr>\r\n");
      out.write("                    \t\t\t\t<td>");
      out.print( company_name );
      out.write("</td>\r\n");
      out.write("                    \t\t\t\t<td>");
      out.print( description );
      out.write("</td>\r\n");
      out.write("                    \t\t\t</tr>\r\n");
      out.write("                    \t\t\t");

                    		}
                    	
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                        </table>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!--TESTIMONIALS -->\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<div class=\"testimonial-area recent-property\" style=\"background-color: #FCFCFC; padding-bottom: 15px;\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-10 col-md-offset-1 col-sm-12 text-center page-title\">\r\n");
      out.write("                        <!-- /.feature title -->\r\n");
      out.write("                        <h2>Our Customers Said  </h2> \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"row testimonial\">\r\n");
      out.write("                        <div class=\"col-md-12\">\r\n");
      out.write("                            <div id=\"testimonial-slider\">\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <div class=\"client-text\">                                \r\n");
      out.write("                                        <p> This website gives us best deals and also very friendly to use.</p>\r\n");
      out.write("                                        <h4><strong>Steel BB, </strong><i>Steel company</i></h4>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"client-face wow fadeInRight\" data-wow-delay=\".9s\"> \r\n");
      out.write("                                        <img src=\"UserTemplate/assets/img/client-face1.png\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <div class=\"client-te xt\">                                \r\n");
      out.write("                                        <p>We find it very useful for our business. It is a grate way to communicate and make good relation globally!</p>\r\n");
      out.write("                                        <h4><strong>PharmaCity, </strong><i>Medicine company</i></h4>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"client-face\">\r\n");
      out.write("                                        <img src=\"UserTemplate/assets/img/client-face2.png\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <div class=\"client-text\">                                \r\n");
      out.write("                                        <p>It is great way to deal with different companies and good in a marketing !</p>\r\n");
      out.write("                                        <h4><strong> Janny AutoParts, </strong><i>Auto part company</i></h4>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"client-face\">\r\n");
      out.write("                                        <img src=\"UserTemplate/assets/img/client-face1.png\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <div class=\"client-text\">                                \r\n");
      out.write("                                        <p>This is best place to communicate and connect with the market!</p>\r\n");
      out.write("                                        <h4><strong>Varma TextStyle, </strong><i>Interior Designer company</i></h4>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"client-face\">\r\n");
      out.write("                                        <img src=\"UserTemplate/assets/img/client-face2.png\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Footer area-->\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<div class=\"footer-area\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\" footer\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 wow fadeInRight animated\">\r\n");
      out.write("                            <div class=\"single-footer\">\r\n");
      out.write("                                <h4>About us </h4>\r\n");
      out.write("                                <div class=\"footer-title-line\"></div>\r\n");
      out.write("\r\n");
      out.write("                                <img src=\"UserTemplate/assets/img/FooterB2BLogo.jpg\" alt=\"\" class=\"wow pulse\" data-wow-delay=\"1s\">\r\n");
      out.write("                                <p>Lorem ipsum dolor cum necessitatibus su quisquam molestias. Vel unde, blanditiis.</p>\r\n");
      out.write("                                <ul class=\"footer-adress\">\r\n");
      out.write("                                    <li><i class=\"pe-7s-map-marker strong\"> </i> 352,353 A , Nr. Bhavik Publications Sarkhej - Gandhinagar Highway, Gota, Ahmedabad, Gujarat 382481</li>\r\n");
      out.write("                                    <li><i class=\"pe-7s-mail strong\"> </i> manthanpatel.30@gmail.com</li>\r\n");
      out.write("                                    <li><i class=\"pe-7s-call strong\"> </i> +91 8469860840</li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 wow fadeInRight animated\">\r\n");
      out.write("                            <div class=\"single-footer\">\r\n");
      out.write("                                <h4>Quick links </h4>\r\n");
      out.write("                                <div class=\"footer-title-line\"></div>\r\n");
      out.write("                                <ul class=\"footer-menu\">\r\n");
      out.write("                                    <li><a href=\"properties.html\">Properties</a>  </li> \r\n");
      out.write("                                    <li><a href=\"#\">Services</a>  </li> \r\n");
      out.write("                                    <li><a href=\"submit-property.html\">Submit property </a></li> \r\n");
      out.write("                                    <li><a href=\"Contact.jsp\">Contact us</a></li> \r\n");
      out.write("                                    <li><a href=\"faq.html\">fqa</a>  </li> \r\n");
      out.write("                                    <li><a href=\"faq.html\">Terms </a>  </li> \r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- <div class=\"col-md-3 col-sm-6 wow fadeInRight animated\">\r\n");
      out.write("                            <div class=\"single-footer\">\r\n");
      out.write("                                <h4>Last News</h4>\r\n");
      out.write("                                <div class=\"footer-title-line\"></div>\r\n");
      out.write("                                <ul class=\"footer-blog\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"col-md-3 col-sm-4 col-xs-4 blg-thumb p0\">\r\n");
      out.write("                                            <a href=\"single.html\">\r\n");
      out.write("                                                <img src=\"UserTemplate/assets/img/demo/small-proerty-2.jpg\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <span class=\"blg-date\">12-12-2016</span>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-8  col-sm-8 col-xs-8  blg-entry\">\r\n");
      out.write("                                            <h6> <a href=\"single.html\">Add news functions </a></h6> \r\n");
      out.write("                                            <p style=\"line-height: 17px; padding: 8px 2px;\">Lorem ipsum dolor sit amet, nulla ...</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li> \r\n");
      out.write("\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"col-md-3 col-sm-4 col-xs-4 blg-thumb p0\">\r\n");
      out.write("                                            <a href=\"single.html\">\r\n");
      out.write("                                                <img src=\"UserTemplate/assets/img/demo/small-proerty-2.jpg\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <span class=\"blg-date\">12-12-2016</span>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-8  col-sm-8 col-xs-8  blg-entry\">\r\n");
      out.write("                                            <h6> <a href=\"single.html\">Add news functions </a></h6> \r\n");
      out.write("                                            <p style=\"line-height: 17px; padding: 8px 2px;\">Lorem ipsum dolor sit amet, nulla ...</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li> \r\n");
      out.write("\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"col-md-3 col-sm-4 col-xs-4 blg-thumb p0\">\r\n");
      out.write("                                            <a href=\"single.html\">\r\n");
      out.write("                                                <img src=\"UserTemplate/assets/img/demo/small-proerty-2.jpg\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <span class=\"blg-date\">12-12-2016</span>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-8  col-sm-8 col-xs-8  blg-entry\">\r\n");
      out.write("                                            <h6> <a href=\"single.html\">Add news functions </a></h6> \r\n");
      out.write("                                            <p style=\"line-height: 17px; padding: 8px 2px;\">Lorem ipsum dolor sit amet, nulla ...</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div> -->\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 wow fadeInRight animated\">\r\n");
      out.write("                            <div class=\"single-footer news-letter\">\r\n");
      out.write("                                <h4>Stay in touch</h4>\r\n");
      out.write("                                <div class=\"footer-title-line\"></div>\r\n");
      out.write("                                <p>Lorem ipsum dolor sit amet, nulla  suscipit similique quisquam molestias. Vel unde, blanditiis.</p>\r\n");
      out.write("\r\n");
      out.write("                                <!-- <form>\r\n");
      out.write("                                    <div class=\"input-group\">\r\n");
      out.write("                                        <input class=\"form-control\" type=\"text\" placeholder=\"E-mail ... \">\r\n");
      out.write("                                        <span class=\"input-group-btn\">\r\n");
      out.write("                                            <button class=\"btn btn-primary subscribe\" type=\"button\"><i class=\"pe-7s-paper-plane pe-2x\"></i></button>\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    </div>                                    \r\n");
      out.write("                                </form> --> \r\n");
      out.write("\r\n");
      out.write("                                <!-- <div class=\"social pull-right\"> \r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a class=\"wow fadeInUp animated\" href=\"https://twitter.com/kimarotec\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("                                        <li><a class=\"wow fadeInUp animated\" href=\"https://www.facebook.com/kimarotec\" data-wow-delay=\"0.2s\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("                                        <li><a class=\"wow fadeInUp animated\" href=\"https://plus.google.com/kimarotec\" data-wow-delay=\"0.3s\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("                                        <li><a class=\"wow fadeInUp animated\" href=\"https://instagram.com/kimarotec\" data-wow-delay=\"0.4s\"><i class=\"fa fa-instagram\"></i></a></li>\r\n");
      out.write("                                        <li><a class=\"wow fadeInUp animated\" href=\"https://instagram.com/kimarotec\" data-wow-delay=\"0.6s\"><i class=\"fa fa-dribbble\"></i></a></li>\r\n");
      out.write("                                    </ul> \r\n");
      out.write("                                </div> -->\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"footer-copy text-center\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"pull-left\">\r\n");
      out.write("                            <span> (C) <a href=\"http://www.mginfosoft.com\">MG Infosoft</a> , All rights reserved 2018  </span> \r\n");
      out.write("                        </div> \r\n");
      out.write("                        <div class=\"bottom-menu pull-right\"> \r\n");
      out.write("                            <ul> \r\n");
      out.write("                                <li><a class=\"wow fadeInUp animated\" href=\"#\" data-wow-delay=\"0.2s\">Home</a></li>\r\n");
      out.write("                                <li><a class=\"wow fadeInUp animated\" href=\"#\" data-wow-delay=\"0.3s\">Paintings</a></li>\r\n");
      out.write("                                <li><a class=\"wow fadeInUp animated\" href=\"#\" data-wow-delay=\"0.4s\">Faq</a></li>\r\n");
      out.write("                                <li><a class=\"wow fadeInUp animated\" href=\"#\" data-wow-delay=\"0.6s\">Contact</a></li>\r\n");
      out.write("                            </ul> \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"UserTemplate/assets/js/modernizr-2.6.2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"UserTemplate/assets/js/jquery-1.10.2.min.js\"></script> \r\n");
      out.write("<script src=\"UserTemplate/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"UserTemplate/assets/js/bootstrap-select.min.js\"></script>\r\n");
      out.write("<script src=\"UserTemplate/assets/js/bootstrap-hover-dropdown.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"UserTemplate/assets/js/easypiechart.min.js\"></script>\r\n");
      out.write("<script src=\"UserTemplate/assets/js/jquery.easypiechart.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"UserTemplate/assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"UserTemplate/assets/js/wow.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"UserTemplate/assets/js/icheck.min.js\"></script>\r\n");
      out.write("<script src=\"UserTemplate/assets/js/price-range.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"assets/js/lightslider.min.js\"></script>\r\n");
      out.write("<script src=\"UserTemplate/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("     $(document).ready(function () {\r\n");
      out.write("\r\n");
      out.write("         $('#image-gallery').lightSlider({\r\n");
      out.write("             gallery: true,\r\n");
      out.write("             item: 1,\r\n");
      out.write("             thumbItem: 9,\r\n");
      out.write("             slideMargin: 0,\r\n");
      out.write("             speed: 500,\r\n");
      out.write("             auto: true,\r\n");
      out.write("             loop: true,\r\n");
      out.write("             onSliderLoad: function () {\r\n");
      out.write("                 $('#image-gallery').removeClass('cS-hidden');\r\n");
      out.write("             }\r\n");
      out.write("         });\r\n");
      out.write("     });\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write(" </script>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
